# Generated by Django 3.1.3 on 2020-11-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0004_auto_20201121_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_roomid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RoomApp.room'),
        ),
    ]
