# Generated by Django 3.1.3 on 2020-11-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0009_merge_20201126_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
    ]
