# Generated by Django 3.1.3 on 2020-11-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0010_remove_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_userid',
        ),
    ]
